# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: RTest


on: [workflow_dispatch, workflow_call]


jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        r-version: ["3.4.0", "3.5.0", "3.6.0", "4.0.0", "4.1.0", "4.2.0"]
    env:
      SIRIUS_USER: ${{ secrets.SIRIUS_USER }}
      SIRIUS_PW: ${{ secrets.SIRIUS_PW }}
    steps:
    - name: Cache Sirius Release
      id: cache-sirius
      uses: actions/cache@v3
      with:
        cache-version: 2
        path: .updater/api/sirius
        key: sirius
    - uses: actions/checkout@v3
    - name: Set up R ${{ matrix.r-version }}
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.r-version }}
    - name: Install Rsirius dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: |
          any::devtools
        working-directory: ./client-api_r/generated
    - name: Build Rsirius
      run: |
        R CMD build ./client-api_r/generated
    - name: Test Rsirius using testthat
      run: |
        R CMD check Rsirius_1.0.0.tar.gz --no-manual
